swagger: '2.0'
info:
  version: 1.0.0
  title: Users
host: "localhost:3000"
tags:
  - name: Users
    description: View and add users
schemes:
  - https
paths:
  /functions/HttpTriggerUsers:
    get:
      tags:
        - Users
      summary: Returns all users
      operationId: get_users
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Users retrieved successfully
          schema:
            $ref: '#/definitions/allUsers'
        '500':
          description: Failure to connect to the database.
    post:
      tags:
        - Users
      summary: Add a new user
      operationId: add_user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Adding a new user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User added successfully.
        '400':
          description: New user request body did not contain the necessary fields.
        '500':
          description: Failure to connect to the database.
definitions:
  allUsers:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userName:
        type: string
  User:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      userPassword:
        type: string