swagger: "2.0"
info:
  version: 1.0.0
  title: users/{user_id}
  description: document the required input and expected output for POST /users/{user_id}
host: nsc-fun-dev-usw2-tuesday.azurewebsites.net

schemes:
  - https

paths:
  /users/{user_id}:
    get:
      tags:
        - users/{user_id}
      summary: Retrieve user by userID
      operationId: getUser
      description: Get user
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          description: Id of the user
          required: true
          type: string
      responses:
        200:
          description: Users retrieved successfully!
          schema:
            $ref: "#/definitions/User"
        400:
          description: Invalid ID supplied
        500:
          description: server error

    post:
      tags:
        - users/{user_id}
      summary: Create user
      operationId: createUser
      description: Create a new user
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          description: Id of the user
          required: true
          type: string
      responses:
        405:
          description: Method not allowed!
        500:
          description: server error

    put:
      tags:
        - users/{user_id}
      summary: Update existing user by userID
      operationId: updateUser
      description: Update a user
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          description: Id of the user
          required: true
          type: string
      responses:
        405:
          description: Method not allowed!
        500:
          description: server error

    delete:
      tags:
        - users/{user_id}
      summary: Delete existing user by userID
      operationId: deleteUser
      description: Delete a user
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          description: Id of the user
          required: true
          type: string
      responses:
        200:
          description: User deleted successfully!
        400:
          description: Invalid ID supplied
        404:
          description: A user with the specified ID was not found
        500:
          description: server error

definitions:
  User:
    type: object
    properties:
      user_id:
        type: integer
        format: int64
      email:
        type: string
      userPassword:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
