# name of action              
name: user/-browser-test
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  #workflow_dispatch: true
  #repository_dispatch: true

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true

      - name: nodeJS and npm version
        run: npm -v

      - name: npm init
        run: npm init -y

      - name: install yarn
        run: npm install --global yarn

      - name: Puppeteer Screenshot Action
        uses: JonathanTreffler/full-website-screenshot-action@v1.0
        with:
          url: https://nscstrdevusw2tuecommon.z5.web.core.windows.net/users
          destination: capture-users-${{ steps.date.outputs.date }}.png

      #Azure Login 
      - name: Azure Login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
            
          #Upload File
      - name: uploading to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.19.1
          inlineScript: az storage blob upload --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }}  --container-name ${{ secrets.BLOB_CONTAINER_SCREENSHOTS }} --file capture-task-id_${{ steps.date.outputs.date }}.png --name capture-task-id_${{ steps.date.outputs.date }}.png