name: Serverless Artillery Users Test

#on:
#  workflow_run:
#    workflows: ["Artillery Users/Id/Tasks/Id Test"]
#    branches: 
#      - development
#      - derek-task1-sprint4
#    types: 
#      - completed

on:
  push:
    branches:
      - development
      - derek-task1-sprint4

jobs:
  slsart-perf:
    name: Serverless Artillery Users Test
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      STAGE_NAME: serverless-perf-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Install Serverless & Serverless Artillery
      - name: Install serverless and serverless-artillery
        run: |
          npm install -g serverless@1.38.0 serverless-artillery

      # Get date for dynamic file saving
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      
      # Run and output serverless test
      - name: Deploy and invoke serverless test
        run: |
          ~/.npm-global/bin/slsart deploy --stage $STAGE_NAME 
          ~/.npm-global/bin/slsart invoke --output serverlessArtilleryReport_userAPI_${{ steps.date.outputs.date }}.json ../../testing/serverless-artillery/serverless-artillery-users.yml
          ~/.npm-global/bin/slsart remove --stage $STAGE_NAME 
      
      - name: Check Serverless Artillery Performance test file
        run: ls -ltr serverlessArtilleryReport_userAPI_${{ steps.date.outputs.date }}.json
        
        #Azure Login 

      - name: Azure Login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
            
        #Upload File
      - name: uploading to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.19.1
          inlineScript: |
            az storage blob upload  --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }}  --container-name ${{ secrets.BLOB_CONTAINER_SERVERLESS_ARTILLERY }}   --name serverlessArtilleryReport_userAPI_${{ steps.date.outputs.date }}.json --file  serverlessArtilleryReport_userAPI_${{ steps.date.outputs.date }}.json
        
        # Azure logout
      - name: logout
        run: |
          az logout